#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: repository-secret
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
secrets:
  - name: repository-secret
  - name: registries-credentials
  - name: cosign
imagePullSecrets:
  - name: repository-secret
  - name: registries-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-sa-permit-deliverable
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deliverable
subjects:
  - kind: ServiceAccount
    name: workload-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-sa-permit-workload
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload
subjects:
  - kind: ServiceAccount
    name: workload-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: cosign
  annotations:
    kpack.io/cosign.docker-media-types: "1"
type: Opaque
data:
  cosign.key: #@ base64.encode('cosign.key')
  cosign.password: #@ base64.encode('cosign.password')
  cosign.pub: #@ base64.encode('cosign.pub')
