---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: dev-sensors
    - name: main-sensors
    - name: feature-sensors
    - name: workshop    
    - name: workshop-s001
      scanpolicy: scan-policy
    - name: workshop-s002
      scanpolicy: scan-policy
    - name: workshop-s003
      scanpolicy: scan-policy
    - name: workshop-s004
      scanpolicy: scan-policy
    - name: workshop-s005
      scanpolicy: scan-policy
    - name: workshop-s006
      scanpolicy: scan-policy
    - name: workshop-s007
      scanpolicy: scan-policy
    - name: workshop-s008
      scanpolicy: scan-policy      
    - name: workshop-s009
      scanpolicy: scan-policy
    - name: workshop-s010
      scanpolicy: scan-policy     
    - name: workshop-s011
      scanpolicy: scan-policy
    - name: workshop-s012
      scanpolicy: scan-policy
    - name: workshop-s013
      scanpolicy: scan-policy
    - name: workshop-s014
      scanpolicy: scan-policy
    - name: workshop-s015
      scanpolicy: scan-policy