---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: workshops-session01-w01-s001-grype
      language: java
      scanpolicy: scan-policy
    #!- name: workshops-w01-s001
    #!  language: java
    #!  scanpolicy: scan-policy
    #!- name: workshops-w01-s002
    #!  language: java
    #!  scanpolicy: scan-policy    
    #!- name: workshops-w01-s003
    #!  language: java
    #!  scanpolicy: scan-policy
    #!- name: workshops-w01-s004
    #!  language: java
    #!  scanpolicy: scan-policy    
    #!- name: workshops-w01-s005
    #!  language: java
    #!  scanpolicy: scan-policy 