---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: demo
      language: java
      scanpolicy: scan-policy
    - name: hae
      language: java
      scanpolicy: scan-policy  
    - name: rick
      language: java
      scanpolicy: scan-policy
    - name: min
      language: java
      scanpolicy: scan-policy
    - name: prod
      language: java
      scanpolicy: scan-policy  