---
apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! This annotation tells the provisioner app to not override this configMap as this is your desired state.
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces:
    - name: dev-sensors
    - name: main-sensors
    - name: workshop-s001
      scanpolicy: scan-policy
    - name: workshop-s002
      scanpolicy: scan-policy
    - name: workshop-s003
      scanpolicy: scan-policy
    - name: workshop-s004
      scanpolicy: scan-policy
    - name: workshop-s005
      scanpolicy: scan-policy
    - name: workshop-s006
      scanpolicy: scan-policy
    - name: workshop-s007
      scanpolicy: scan-policy
    - name: workshop-s008
      scanpolicy: scan-policy      
    - name: workshop-s009
      scanpolicy: scan-policy
    - name: workshop-s010
      scanpolicy: scan-policy     
    - name: workshop-s011
      scanpolicy: scan-policy
    - name: workshop-s012
      scanpolicy: scan-policy
    - name: workshop-s013
      scanpolicy: scan-policy
    - name: workshop-s014
      scanpolicy: scan-policy
    - name: workshop-s015
      scanpolicy: scan-policy
    - name: workshop-s016
      scanpolicy: scan-policy
    - name: workshop-s017
      scanpolicy: scan-policy
    - name: workshop-s018
      scanpolicy: scan-policy      
    - name: workshop-s019
      scanpolicy: scan-policy
    - name: workshop-s020
      scanpolicy: scan-policy  
    - name: workshop-s021
      scanpolicy: scan-policy
    - name: workshop-s022
      scanpolicy: scan-policy
    - name: workshop-s023
      scanpolicy: scan-policy
    - name: workshop-s024
      scanpolicy: scan-policy
    - name: workshop-s025
      scanpolicy: scan-policy
    - name: workshop-s026
      scanpolicy: scan-policy
    - name: workshop-s027
      scanpolicy: scan-policy
    - name: workshop-s028
      scanpolicy: scan-policy      
    - name: workshop-s029
      scanpolicy: scan-policy
    - name: workshop-s030
      scanpolicy: scan-policy