#@ load("@ytt:overlay", "overlay")
#@ def customize():

#! rewrite the default serviceaccount secrets/ requires gitlab-workload-token and github-workload-token secrets from /custom-resources/workload-sa/workload-sa-with-secrets.yaml
#@overlay/match by=overlay.subset({"apiVersion": "v1", "kind": "ServiceAccount","metadata":{"name":"default"}}), expects="0+"
---
secrets:
  - name: repository-secret
  - name: registries-credentials
imagePullSecrets:
  - name: rrepository-secret
  - name: registries-credentials

#@overlay/match by=overlay.subset({"kind":"ScanTemplate"}),expects="1+"
---
apiVersion: v1
data:
  grype-airgap-overlay-secrets.yaml: I0AgbG9hZCgiQHl0dDpvdmVybGF5IiwgIm92ZXJsYXkiKQojQG92ZXJsYXkvbWF0Y2ggYnk9b3ZlcmxheS5zdWJzZXQoeyJraW5kIjoiU2NhblRlbXBsYXRlIn0pLGV4cGVjdHM9IjErIgotLS0Kc3BlYzoKICB0ZW1wbGF0ZToKICAgIGluaXRDb250YWluZXJzOgogICAgICAjQG92ZXJsYXkvbWF0Y2ggYnk9b3ZlcmxheS5zdWJzZXQoeyJuYW1lIjogInNjYW4tcGx1Z2luIn0pLCBleHBlY3RzPSIxKyIKICAgICAgLSBuYW1lOiBzY2FuLXBsdWdpbgogICAgICAgICNAb3ZlcmxheS9tYXRjaCBtaXNzaW5nX29rPVRydWUKICAgICAgICBlbnY6CiAgICAgICAgICAjQG92ZXJsYXkvYXBwZW5kCiAgICAgICAgICAtIG5hbWU6IEdSWVBFX0NIRUNLX0ZPUl9BUFBfVVBEQVRFCiAgICAgICAgICAgIHZhbHVlOiAiZmFsc2UiCiAgICAgICAgICAtIG5hbWU6IEdSWVBFX0RCX0FVVE9fVVBEQVRFCiAgICAgICAgICAgIHZhbHVlOiAidHJ1ZSIKICAgICAgICAgIC0gbmFtZTogR1JZUEVfREJfTUFYX0FMTE9XRURfQlVJTFRfQUdFCiAgICAgICAgICAgIHZhbHVlOiAxMjAwMDBoCg==
kind: Secret
metadata:
  name: grype-airgap-overlay
type: Opaque


#@  end
