#@ load("@ytt:data", "data") 
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline-nodejs
  namespace: #@ data.values.name
  labels:
    apps.tanzu.vmware.com/pipeline: test
    apps.tanzu.vmware.com/language: nodejs
spec:
  params:
  - name: source-url
  - name: source-revision
  tasks:
  - name: node-test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
        - name: test
          image: tapworkshop.azurecr.io/library/node:latest
          script: |-
            cd `mktemp -d`
            wget -qO- $(params.source-url) | tar xvz -m
            npm install-test
            echo "NodeJS Test OK!!" 
