#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing', 'testing_scanning']) and in_list('profile', ['full', 'iterate', 'build']):
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline-python
  namespace: #@ data.values.name
  labels:
    apps.tanzu.vmware.com/pipeline: "test"
    apps.tanzu.vmware.com/language: "python"
spec:
  params:
  - name: source-url
  - name: source-revision
  workspaces:
  - name: supplychain-workspace
  tasks:
  - name: python-test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      steps:
        - name: python-test
          image: tapworkshop.azurecr.io/library/python:3
          script: |-
            set -ex
            cd `mktemp -d`
            #wget -qO- $(params.source-url) | tar xvz -m
            #pytest
            pip install --no-cache-dir -r requirements.txt
            echo " python Test SKip OK!!"
